[package]
name = "logic-analyzer-platform"
version.workspace = true
edition = "2024"
authors = ["Rob Caelers <rob.caelers@gmail.com>"]

[dependencies]
egui = { workspace = true }
input-bindings = { path = "../input_bindings" }
logic-analyzer-ui = { path = "../logic_analyzer_ui" }
node-graph = { path = "../widgets/node_graph" }
serde_json = { workspace = true }
signal-processing = { path = "../signal_processing" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam-channel = { workspace = true }
dirs = { workspace = true }
rfd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
