[package]
name = "trigger-editor"
version.workspace = true
edition = "2024"
authors = ["Rob Caelers <rob.caelers@gmail.com>"]

[lib]
name = "trigger_editor"
path = "src/lib.rs"

[dependencies]
egui = { workspace = true }
signal-capture = { path = "../../signal_capture" }
thiserror = { workspace = true }
logic-analyzer-trigger = { path = "../../logic_analyzer_trigger" }
