[package]
name = "logic-analyzer-graph-registry"
version.workspace = true
edition = "2024"
authors = ["Rob Caelers <rob.caelers@gmail.com>"]

[lib]
name = "logic_analyzer_graph_registry"
path = "src/lib.rs"

[dependencies]
inventory = { workspace = true }
logic-analyzer-graph-capabilities = { path = "../logic_analyzer_graph_capabilities" }
node-graph = { path = "../widgets/node_graph" }
serde_json = { workspace = true }
signal-capture = { workspace = true }
signal-derived = { workspace = true }
signal-runtime = { workspace = true }
