[package]
name = "logic-analyzer-graph-editor-registry"
version.workspace = true
edition = "2024"
authors = ["Rob Caelers <rob.caelers@gmail.com>"]

[lib]
name = "logic_analyzer_graph_editor_registry"
path = "src/lib.rs"

[dependencies]
inventory = { workspace = true }
node-graph = { path = "../widgets/node_graph" }
